;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #BCC3C3
background-alt = #002B36
foreground = #002B36
foreground-alt = #BCC3C3
primary = #ffb52a
secondary = #e60053
alert = #FF0000

[bar/default]
monitor = ${env:MONITOR:}
width = 100%
height = 30
radius = 0.0
fixed-center = true
top = no
bottom = yes
override-redirect = false

foreground = ${colors.foreground-alt}
background = ${colors.background-alt}

; Under-/overline pixel size and argb color
; Individual values can be defined using:
;   {overline,underline}-size
;   {overline,underline}-color
line-size = 1
line-color = #dfdfdf

border-top-size = 0
border-bottom-size = 0
border-left-size = 0
border-right-size = 0

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 1

font-1 = Hack:pixelsize=9;3
font-0 = FontAwesome:style=Regular;3

separator = " | "
modules-left = i3
modules-center = date
modules-right = memory cpu network volume battery

wm-restack = i3
cursor-click = pointer

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = false
enable-click = false
enable-scroll = false

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.foreground-alt}
label-mode-background = ${colors.background-alt}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.foreground-alt}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = ${self.label-focused-padding}
label-unfocused-foreground = ${colors.foreground-alt}
label-unfocused-background = ${colors.background-alt}

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-foreground = ${self.label-focused-background}
label-visible-background = ${self.label-focused-foreground}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; Separator in between workspaces
label-separator =
label-separator-padding = 0
label-separator-foreground = #fff

[module/linux-ver]
type = custom/script
exec = uname -r
interval = 600

[module/updates]
type = custom/script
exec = ~/dotfiles/scripts/arch_updates.sh
interval = 60
label = %output%

[module/date]
type = internal/date
interval = 1

time = "%H:%M %a, %d. %b %Y"

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-background = ${colors.background-alt}

label = %time%
label-foreground = ${colors.foreground-alt}
label-background = ${colors.background-alt}

[module/volume]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
sink = alsa_output.pci-0000_00_1f.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Reverses the increment/decrement on scroll event. Set this to true if you are
; using natural scrolling option on your touchpad.
; New in version 3.7.0
; Default: false
reverse-scroll = false

format-volume = <label-volume>
format-muted = <label-muted>
label-volume =  %percentage%%
label-muted = 

[module/network]
type = internal/network
interface = wlan0
interval = 3.0
accumulate-stats = true
unknown-as-up = false
speed-unit = ""
format-connected = <label-connected>
format-disconnected = <label-disconnected>
format-packetloss = <label-packetloss> <label-connected>

label-connected = %{F#089908} %{F#00ff00}%downspeed% %{F#990808} %{F#ff0000}%upspeed%%{F-}
label-disconnected = NO WIFI
label-disconnected-foreground = #ff0000
label-packetloss = [!]
label-packetloss-foreground = #ff0000

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98
low-at = 20
poll-interval = 1
format-charging =  %{F#00ff00}<label-charging>%{F-}
format-full =  %{F#00ff00}<label-full>%{F-}
format-discharging =  %{F#ffee8c}<label-discharging>%{F-}
format-low = %{F#ff0000}<label-low>%{F-}
label-charging = %percentage%%
label-discharging = ${self.label-charging}
label-low = ${self.label-charging}
label-full = ${self.label-charging}

[module/cpu]
type = internal/cpu
interval = 0.5
warn-percentage = 101
format = <label>
label =  %percentage%%

[module/memory]
type = internal/memory
interval = 1
warn-percentage = 101
format = <label>
label = %{F#ff0000}%percentage_used%% %{F-}/%{F#00ff00} %percentage_free%% %{F-}

[settings]
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 5
